import { readFileSync, existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execSync } from 'node:child_process';

interface BugAnalysis {
  title: string;
  summary: string;
  stepsToReproduce: string[];
  expectedResult: string;
  actualResult: string;
  failureType: string;
  severity: string;
  priority: string;
  classification: string;
  confidence: number;
  relevantEvidence?: string[];
  error?: string;
}

interface CreatedIssue {
  number: number;
  title: string;
  html_url: string;
  state: string;
}

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = join(__dirname, '..');

function getRepoInfo(): { owner: string; repo: string } {
  try {
    const remote = execSync('git config --get remote.origin.url', { cwd: rootDir, encoding: 'utf-8' }).trim();
    const match = remote.match(/(?:git@github\.com:|https:\/\/github\.com\/)([^\/\s]+)\/([^\/\s]+?)(?:\.git)?$/);
    if (match) {
      return { owner: match[1], repo: match[2] };
    }
  } catch {
    // ignore
  }
  throw new Error('Could not determine GitHub repository from git remote.');
}

function getWorkflowRunInfo(): { workflowRunUrl: string } {
  const runId = process.env.GITHUB_RUN_ID || '';
  const repo = getRepoInfo();
  const workflowRunUrl = runId
    ? `https://github.com/${repo.owner}/${repo.repo}/actions/runs/${runId}`
    : '';
  return { workflowRunUrl };
}

function loadValidatedBugs(): Array<BugAnalysis & { validation?: { valid: boolean; issues: string[]; correctedBug?: BugAnalysis } }> {
  const path = join(rootDir, 'validated-bug.json');
  if (!existsSync(path)) {
    console.error('No validated-bug.json found. Run validate-with-copilot.ts first.');
    process.exit(1);
  }
  const data = JSON.parse(readFileSync(path, 'utf-8'));
  if (data.length === 0) {
    console.log('No validated bugs found.');
    process.exit(0);
  }
  return data;
}

async function createIssue(bug: BugAnalysis, owner: string, repo: string, token: string, workflowRunUrl: string): Promise<CreatedIssue> {
  const stepsList = bug.stepsToReproduce.map((step, i) => `${i + 1}. ${step}`).join('\n');

  const classificationLabel = bug.classification === 'PRODUCT_BUG' ? 'Product Bug' : bug.classification;

  const body = `## Summary

${bug.summary}

## AI Classification

- **Classification**: ${classificationLabel}
- **Confidence**: ${(bug.confidence * 100).toFixed(0)}%

## Steps to Reproduce

${stepsList}

## Expected Result

${bug.expectedResult}

## Actual Result

${bug.actualResult}

## Test

\`${bug.title}\`

## Environment

- Failure Type: ${bug.failureType}
- CI: GitHub Actions
- Branch: unknown
- Commit: unknown

## Evidence

### GitHub Actions

[View workflow run](${workflowRunUrl})

---

**Generated by AI QA Bug Reporting**`;

  const response = await fetch(`https://api.github.com/repos/${owner}/${repo}/issues`, {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${token}`,
      'Accept': 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
      'Content-Type': 'application/json',
      'User-Agent': 'AI-QA-Bug-Reporting',
    },
    body: JSON.stringify({
      title: `[${classificationLabel}] ${bug.title}`,
      body,
      labels: [bug.priority, bug.severity, `failure:${bug.failureType.toLowerCase()}`, `classification:${bug.classification.toLowerCase()}`],
    }),
  });

  if (!response.ok) {
    const errorBody = await response.text();
    throw new Error(`GitHub API error creating issue: ${response.status} ${errorBody}`);
  }

  return response.json() as Promise<CreatedIssue>;
}

async function main() {
  console.log('Creating GitHub Issues from validated bugs...');

  const token = process.env.GITHUB_TOKEN;
  if (!token) {
    console.error('GITHUB_TOKEN environment variable is not set.');
    process.exit(1);
  }

  const bugs = loadValidatedBugs();
  const { owner, repo } = getRepoInfo();
  const { workflowRunUrl } = getWorkflowRunInfo();

  const createdIssues: Array<{ bug: BugAnalysis; issue: CreatedIssue; labels: string[] }> = [];
  const failedIssues: Array<{ bug: BugAnalysis; error: string }> = [];

  console.log('');
  console.log('========================================');
  console.log('GitHub Issue Creation');
  console.log('========================================');
  console.log(`Bug candidates: ${bugs.length}`);
  console.log('========================================');

  for (const bug of bugs) {
    const classification = bug.classification || 'UNKNOWN';

    if (classification === 'TEST_INFRASTRUCTURE' || classification === 'TEST_DEFECT') {
      console.log(`  Skipping "${bug.title}" — classification is ${classification} (infrastructure/test issues excluded).`);
      continue;
    }

    console.log(`  Creating issue: [${classification}] ${bug.title}`);
    try {
      const issue = await createIssue(bug, owner, repo, token, workflowRunUrl);
      console.log(`  → Issue #${issue.number}: ${issue.html_url}`);
      createdIssues.push({ bug, issue, labels: [] });
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      console.error(`  → Failed: ${message}`);
      failedIssues.push({ bug, error: message });
    }
  }

  const outputPath = join(rootDir, 'created-issues.json');
  const outputDir = dirname(outputPath);
  if (!existsSync(outputDir)) {
    mkdirSync(outputDir, { recursive: true });
  }

  writeFileSync(outputPath, JSON.stringify(createdIssues, null, 2));

  console.log('');
  console.log('========================================');
  console.log('GitHub Issue Creation Summary');
  console.log('========================================');
  console.log(`Bug candidates: ${bugs.length}`);
  console.log(`Issues created: ${createdIssues.length}`);
  console.log(`Issues failed: ${failedIssues.length}`);
  console.log('========================================');

  if (failedIssues.length > 0) {
    console.error('');
    console.error('ERROR: GitHub issue creation failed for some bugs.');
    process.exit(1);
  }

  console.log(`Created issues written to: ${outputPath}`);
}

main();
